apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webhook
        app.kubernetes.io/version: v1.19.2
        helm.sh/chart: cert-manager-v1.19.2
    name: cert-manager-webhook
    namespace: cert-manager
spec:
    minAvailable: 1
    selector:
        matchLabels:
            app.kubernetes.io/component: webhook
            app.kubernetes.io/instance: cert-manager
            app.kubernetes.io/name: webhook
