apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    labels:
        app: webhook
        app.kubernetes.io/component: webhook
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webhook
        app.kubernetes.io/version: v1.19.2
        helm.sh/chart: cert-manager-v1.19.2
    name: cert-manager-webhook:subjectaccessreviews
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cert-manager-webhook:subjectaccessreviews
subjects:
    - kind: ServiceAccount
      name: cert-manager-webhook
      namespace: cert-manager
