apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    labels:
        app: cert-manager
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: cert-manager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cert-manager
        app.kubernetes.io/version: v1.19.2
        helm.sh/chart: cert-manager-v1.19.2
    name: cert-manager-tokenrequest
    namespace: cert-manager
rules:
    - apiGroups:
        - ""
      resourceNames:
        - cert-manager
      resources:
        - serviceaccounts/token
      verbs:
        - create
