---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr
  labels:
    app: prowlarr
    app.kubernetes.io/name: prowlarr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
    app.kubernetes.io/name: prowlarr
spec:
  selector:
    app.kubernetes.io/name: prowlarr
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
    app.kubernetes.io/name: prowlarr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
        app.kubernetes.io/name: prowlarr
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: austin
      containers:
      - name: prowlarr
        image: lscr.io/linuxserver/prowlarr:latest
        env:
        - name: TZ
          value: America/Chicago
        volumeMounts:
          - name: prowlarr-config
            mountPath: /config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        readinessProbe:
          tcpSocket:
            port: http
          failureThreshold: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 9696
      volumes:
      - name: prowlarr-config
        persistentVolumeClaim:
            claimName: prowlarr
