apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
    labels:
        app.kubernetes.io/instance: vmks
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-k8s-stack
        app.kubernetes.io/version: v1.131.0
        helm.sh/chart: victoria-metrics-k8s-stack-0.65.1
    name: vmks-victoria-metrics-k8s-stack-core-dns
    namespace: victoria-metrics
spec:
    endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
    jobLabel: jobLabel
    namespaceSelector:
        matchNames:
            - kube-system
    selector:
        matchLabels:
            app: vmks-victoria-metrics-k8s-stack-core-dns
            app.kubernetes.io/instance: vmks
            app.kubernetes.io/name: victoria-metrics-k8s-stack
            jobLabel: core-dns
