apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
    labels:
        app: victoria-metrics-k8s-stack
        app.kubernetes.io/instance: victoria-metrics
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-k8s-stack
        app.kubernetes.io/version: v0.28.1
        helm.sh/chart: victoria-metrics-k8s-stack-0.65.1
    name: victoria-metrics-victoria-metrics-k8s-stack-kubernetes-system
    namespace: victoria-metrics
spec:
    groups:
        - name: kubernetes-system
          params: {}
          rules:
            - alert: KubeVersionMismatch
              annotations:
                description: There are {{ $value }} different semantic versions of Kubernetes components running on cluster {{ $labels.cluster }}.
                runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeversionmismatch
                summary: Different semantic versions of Kubernetes components running.
              expr: count(count(label_replace(kubernetes_build_info{job!~"kube-dns|coredns"}, "git_version", "$1", "git_version", "(v[0-9]*.[0-9]*).*")) by(git_version,cluster)) by(cluster) > 1
              for: 15m
              labels:
                severity: warning
            - alert: KubeClientErrors
              annotations:
                description: Kubernetes API server client '{{ $labels.job }}/{{ $labels.instance }}' is experiencing {{ $value | humanizePercentage }} errors on cluster {{ $labels.cluster }}.
                runbook_url: https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeclienterrors
                summary: Kubernetes API server client is experiencing errors.
              expr: (sum(rate(rest_client_requests_total{job="apiserver",code=~"5.."}[5m])) by(cluster,instance,job,namespace) / sum(rate(rest_client_requests_total{job="apiserver"}[5m])) by(cluster,instance,job,namespace)) > 0.01
              for: 15m
              labels:
                severity: warning
