apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
    labels:
        app: victoria-metrics-k8s-stack
        app.kubernetes.io/instance: vmks
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-k8s-stack
        app.kubernetes.io/version: v0.28.1
        helm.sh/chart: victoria-metrics-k8s-stack-0.65.1
    name: vmks-victoria-metrics-k8s-stack-node.rules
    namespace: victoria-metrics
spec:
    groups:
        - name: node.rules
          params: {}
          rules:
            - annotations: {}
              expr: topk(1, max(label_replace(kube_pod_info{job="kube-state-metrics",node!=""}, "pod", "$1", "pod", "(.*)")) by(cluster,node,namespace,pod)) by(cluster,namespace,pod)
              labels: {}
              record: 'node_namespace_pod:kube_pod_info:'
            - annotations: {}
              expr: count(node_cpu_seconds_total{mode="idle",job="node-exporter"} * on(cluster,namespace,pod) group_left(node) topk(1, node_namespace_pod:kube_pod_info:) by(cluster,namespace,pod)) by(cluster,node)
              labels: {}
              record: node:node_num_cpu:sum
            - annotations: {}
              expr: sum(node_memory_MemAvailable_bytes{job="node-exporter"} or (((node_memory_Buffers_bytes{job="node-exporter"} + node_memory_Cached_bytes{job="node-exporter"}) + node_memory_MemFree_bytes{job="node-exporter"}) + node_memory_Slab_bytes{job="node-exporter"})) by(cluster)
              labels: {}
              record: :node_memory_MemAvailable_bytes:sum
            - annotations: {}
              expr: avg(sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait",mode!="steal",job="node-exporter"}[5m])) without(mode)) by(cluster,node)
              labels: {}
              record: node:node_cpu_utilization:ratio_rate5m
            - annotations: {}
              expr: avg(node:node_cpu_utilization:ratio_rate5m) by(cluster)
              labels: {}
              record: cluster:node_cpu:ratio_rate5m
