apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
    labels:
        app: victoria-metrics-k8s-stack
        app.kubernetes.io/instance: victoria-metrics
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: victoria-metrics-k8s-stack
        app.kubernetes.io/version: v0.28.1
        helm.sh/chart: victoria-metrics-k8s-stack-0.65.1
    name: victoria-metrics-victoria-metrics-k8s-stack-kube-apiserver-availability.rules
    namespace: victoria-metrics
spec:
    groups:
        - interval: 3m
          name: kube-apiserver-availability.rules
          params: {}
          rules:
            - annotations: {}
              expr: (avg_over_time(code_verb:apiserver_request_total:increase1h[30d]) * 24) * 30
              labels: {}
              record: code_verb:apiserver_request_total:increase30d
            - annotations: {}
              expr: sum(code_verb:apiserver_request_total:increase30d{verb=~"LIST|GET"}) by(cluster,code)
              labels:
                verb: read
              record: code:apiserver_request_total:increase30d
            - annotations: {}
              expr: sum(code_verb:apiserver_request_total:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) by(cluster,code)
              labels:
                verb: write
              record: code:apiserver_request_total:increase30d
            - annotations: {}
              expr: sum(increase(apiserver_request_sli_duration_seconds_bucket[1h])) by(cluster,verb,scope,le)
              labels: {}
              record: cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h
            - annotations: {}
              expr: sum((avg_over_time(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h[30d]) * 24) * 30) by(cluster,verb,scope,le)
              labels: {}
              record: cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d
            - annotations: {}
              expr: sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase1h{le="+Inf"}) by(cluster,verb,scope)
              labels: {}
              record: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase1h
            - annotations: {}
              expr: sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{le="+Inf"}) by(cluster,verb,scope)
              labels: {}
              record: cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d
            - annotations: {}
              expr: 1 - ((((sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) by(cluster) - sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"POST|PUT|PATCH|DELETE",le=~"1(\\.0)?"} or vector(0)) by(cluster)) + (sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"LIST|GET"}) by(cluster) - ((sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope=~"resource|",le=~"1(\\.0)?"} or vector(0)) by(cluster) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="namespace",le=~"5(\\.0)?"} or vector(0)) by(cluster)) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="cluster",le=~"30(\\.0)?"} or vector(0)) by(cluster)))) + sum(code:apiserver_request_total:increase30d{code=~"5.."} or vector(0)) by(cluster)) / sum(code:apiserver_request_total:increase30d) by(cluster))
              labels:
                verb: all
              record: apiserver_request:availability30d
            - annotations: {}
              expr: 1 - (((sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"LIST|GET"}) by(cluster) - ((sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope=~"resource|",le=~"1(\\.0)?"} or vector(0)) by(cluster) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="namespace",le=~"5(\\.0)?"} or vector(0)) by(cluster)) + sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"LIST|GET",scope="cluster",le=~"30(\\.0)?"} or vector(0)) by(cluster))) + sum(code:apiserver_request_total:increase30d{verb="read",code=~"5.."} or vector(0)) by(cluster)) / sum(code:apiserver_request_total:increase30d{verb="read"}) by(cluster))
              labels:
                verb: read
              record: apiserver_request:availability30d
            - annotations: {}
              expr: 1 - (((sum(cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d{verb=~"POST|PUT|PATCH|DELETE"}) by(cluster) - sum(cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d{verb=~"POST|PUT|PATCH|DELETE",le=~"1(\\.0)?"} or vector(0)) by(cluster)) + sum(code:apiserver_request_total:increase30d{verb="write",code=~"5.."} or vector(0)) by(cluster)) / sum(code:apiserver_request_total:increase30d{verb="write"}) by(cluster))
              labels:
                verb: write
              record: apiserver_request:availability30d
            - annotations: {}
              expr: sum(rate(apiserver_request_total{job="apiserver",verb=~"LIST|GET"}[5m])) by(cluster,code,resource)
              labels:
                verb: read
              record: code_resource:apiserver_request_total:rate5m
            - annotations: {}
              expr: sum(rate(apiserver_request_total{job="apiserver",verb=~"POST|PUT|PATCH|DELETE"}[5m])) by(cluster,code,resource)
              labels:
                verb: write
              record: code_resource:apiserver_request_total:rate5m
            - annotations: {}
              expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"2.."}[1h])) by(cluster,code,verb)
              labels: {}
              record: code_verb:apiserver_request_total:increase1h
            - annotations: {}
              expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"3.."}[1h])) by(cluster,code,verb)
              labels: {}
              record: code_verb:apiserver_request_total:increase1h
            - annotations: {}
              expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"4.."}[1h])) by(cluster,code,verb)
              labels: {}
              record: code_verb:apiserver_request_total:increase1h
            - annotations: {}
              expr: sum(increase(apiserver_request_total{job="apiserver",verb=~"LIST|GET|POST|PUT|PATCH|DELETE",code=~"5.."}[1h])) by(cluster,code,verb)
              labels: {}
              record: code_verb:apiserver_request_total:increase1h
