apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/instance: vmks
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.3.0
        helm.sh/chart: grafana-10.1.5
    name: vmks-grafana
    namespace: victoria-metrics
