apiVersion: v1
data:
    admin-password: WnZMendSYkQ5dm9uSTNlZ1JHSVNKbDdZZVhzVFZ5VlpxZTg1RHF6YQ==
    admin-user: YWRtaW4=
    ldap-toml: ""
kind: Secret
metadata:
    labels:
        app.kubernetes.io/component: admin-secret
        app.kubernetes.io/instance: victoria-metrics
        app.kubernetes.io/name: grafana
        app.kubernetes.io/version: 12.3.0
        helm.sh/chart: grafana-10.1.5
    name: victoria-metrics-grafana
    namespace: victoria-metrics
type: Opaque
