resources:
- github.com/kasuboski/feedreader/deploy/manifests?ref=main
- github.com/kasuboski/tailscale-proxy/k8s?ref=main
- sa.yaml

patchesStrategicMerge:
  - add-config.yaml
  - add-litestream.yaml
  - add-tailscale-proxy.yaml

configMapGenerator:
  - name: feeds
    files:
    - "feeds.opml"

images:
  - name: litestream/litestream
    newTag: 0.3.9
  - name: ghcr.io/kasuboski/feedreader
    newTag: sha-cd3ae95
  - name: ghcr.io/kasuboski/tailscale-proxy
    newTag: sha-fdcf45d
