# This still doesn't shut down reliably and seems to just hang eventually
apiVersion: batch/v1
kind: Job
metadata:
  name: media-sync
  labels:
    app: media-sync
    app.kubernetes.io/name: media-sync
spec:
  backoffLimit: 3
  template:
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: austin
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      restartPolicy: OnFailure
      containers:
      - name: sync
        image: rclone/rclone
        args:
        - sync
        - --check-first
        - --human-readable
        - --stats-log-level=NOTICE
        - --order-by=size,asc # send smaller files first
        - --max-duration=4h
        - --exclude=downloads/**
        - --exclude=downloads-complete/**
        - --exclude=Music/**
        - --exclude=plex-bak/**
        - /speicher
        - /sichy
        volumeMounts:
        - name: speicher
          mountPath: /speicher
        - name: sichy
          mountPath: /sichy
        resources: {}
      volumes:
      - name: speicher
        persistentVolumeClaim:
          claimName: media-speicher
      - name: sichy
        persistentVolumeClaim:
          claimName: media-sichy