apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fettig.lan
    path: "/storage"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - home
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - austin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  volumeName: storage
  resources:
    requests:
      storage: 1Mi
