---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
    app.kubernetes.io/name: sabnzbd
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
    app.kubernetes.io/name: sabnzbd
spec:
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
  - name: http
    port: 80
    targetPort: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  strategy:
    type: Recreate
  selector:
      matchLabels:
        app.kubernetes.io/name: sabnzbd
  template:
    metadata:
      labels:
        app: sabnzbd
        app.kubernetes.io/name: sabnzbd
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: austin
      securityContext:
        fsGroup: 1000
      containers:
      - name: sabnzbd
        image: lscr.io/linuxserver/sabnzbd
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Chicago
        volumeMounts:
        - name: sabnzbd-config
          mountPath: /config
        - name: data
          subPath: downloads
          mountPath: /downloads
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 2000m
            memory: 2Gi
        ports:
          - name: web
            containerPort: 8080 
      volumes:
        - name: sabnzbd-config
          persistentVolumeClaim:
              claimName: sabnzbd
        - name: data
          persistentVolumeClaim:
              claimName: adel-speicher
