apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: austin-advertisement
spec:
  ipAddressPools:
  - austin-ips
  nodeSelectors:
  - matchLabels:
      topology.kubernetes.io/zone: austin

