apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: vouch
spec:
  ingressClassName: external-nginx
  rules:
  - host: vouch.joshcorp.co
    http:
      paths:
      - backend:
          service:
            name: vouch
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - vouch.joshcorp.co
    secretName: vouch-joshcorp-tls
---
apiVersion: v1
kind: Service
metadata:
  name: vouch
spec:
  selector:
    app: vouch
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vouch
spec:
  selector:
    matchLabels:
      app: vouch
  template:
    metadata:
      labels:
        app: vouch
    spec:
      containers:
      - name: vouch
        image: voucher/vouch-proxy:latest-arm
        resources:
          limits:
            memory: "32Mi"
            cpu: "50m"
        ports:
        - name: http
          containerPort: 9090
        env:
        - name: VOUCH_PORT
          value: '9090'
        volumeMounts:
          - name: vouch-config
            mountPath: /config
            readOnly: true
      volumes:
        - name: vouch-config
          configMap:
            name: vouch-config
