apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-austin
  labels:
    app: plex-austin
    app.kubernetes.io/name: plex-austin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: plex-austin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: plex-austin
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: austin
      containers:
      - name: plex
        image: plexinc/pms-docker
        ports:
        - name: tcp-plex
          containerPort: 32400
        env:
        - name: TZ
          value: America/Chicago
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: /data
        resources:
          limits:
            gpu.intel.com/i915: "1"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-austin
      - name: data
        persistentVolumeClaim:
          claimName: media-speicher
---
apiVersion: v1
kind: Service
metadata:
  name: plex-austin
  labels:
    app: plex-austin
    app.kubernetes.io/name: plex-austin
spec:
  type: NodePort
  ports:
  - name: tcp-plex
    port: 32400
    targetPort: tcp-plex
    nodePort: 32400
  selector:
    app.kubernetes.io/name: plex-austin


