apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kasuboski/k8s-gitops.git
    targetRevision: main
    path: gitops/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
