apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system # annoying
spec:
  template:
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
