apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/name: joshcorp-landing
  name: joshcorp-landing
spec:
  ingressClassName: external-nginx
  rules:
  - host: joshcorp.co
    http:
      paths:
      - backend:
          service:
            name: joshcorp-landing
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
        