apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/name: transmission
  name: transmission
spec:
  ingressClassName: external-nginx
  rules:
  - host: transmission.joshcorp.co
    http:
      paths:
      - backend:
          service:
            name: transmission
            port:
              name: http
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - transmission.joshcorp.co
    secretName: transmission-joshcorp-tls
