# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm template ingress-nginx ingress-nginx/ingress-nginx --version 4.5.0 -f ingress/nginx-ingress-values.yaml --namespace ingress-nginx > ingress/ingress-nginx.yaml
controller:
  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.86.240
  ingressClassResource:
    name: external-nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/external-ingress-nginx"
  ingressClass: external-nginx
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false