# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm template ingress-nginx ingress-nginx/ingress-nginx --version 4.5.0 -f ingress/nginx-ingress-values.yaml --namespace ingress-nginx > ingress/ingress-nginx.yaml
controller:
  service:
    type: ClusterIP
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false