---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr
  labels:
    app: lidarr
    app.kubernetes.io/name: lidarr
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels:
    app: lidarr
    app.kubernetes.io/name: lidarr
spec:
  selector:
    app.kubernetes.io/name: lidarr
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app: lidarr
    app.kubernetes.io/name: lidarr
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app: lidarr
        app.kubernetes.io/name: lidarr
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: austin
      containers:
      - name: lidarr
        image: lscr.io/linuxserver/lidarr
        env:
        - name: TZ
          value: America/Chicago
        volumeMounts:
          - name: lidarr-config
            mountPath: /config
          - name: media
            subPath: Music
            mountPath: /music
          - name: media
            subPath: downloads
            mountPath: /downloads
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          failureThreshold: 5
          timeoutSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          failureThreshold: 5
          timeoutSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
        ports:
        - name: http
          containerPort: 8686
      volumes:
      - name: lidarr-config
        persistentVolumeClaim:
            claimName: lidarr
      - name: media
        persistentVolumeClaim:
            claimName: media-storage

