{
 "title": "Grafana Overview",
 "tags": [ "vm-k8s-stack" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(grafana_build_info, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grafana_build_info, instance)"
    }
   },
   { "name": "cluster", "label": "cluster", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Firing Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "grafana_alerting_result_total{job=~\"$job\",instance=~\"$instance\",state=\"alerting\",cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Dashboards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(grafana_stat_totals_dashboard{job=~\"$job\",instance=~\"$instance\",cluster=~\"$cluster\"}) by(cluster)"
    }
   ]
  },
  {
   "title": "Build Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "grafana_build_info{job=~\"$job\",instance=~\"$instance\",cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(grafana_http_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\",cluster=~\"$cluster\"}[1m])) by(status_code,cluster)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(grafana_http_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[$__rate_interval])) by(le,cluster)) * 1",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(irate(grafana_http_request_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[$__rate_interval])) by(le,cluster)) * 1",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "(sum(irate(grafana_http_request_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[$__rate_interval])) by(cluster) * 1) / sum(irate(grafana_http_request_duration_seconds_count{instance=~\"$instance\",job=~\"$job\",cluster=~\"$cluster\"}[$__rate_interval])) by(cluster)",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}