resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.6.2
- ingress.yaml

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-rbac-cm.yaml
- argocd-cmd-params-cm.yaml
- network-policy.yaml

namespace: argocd
