on:
  workflow_dispatch: {}
  push:
    paths:
    - 'ingress/cloudflared/config.yaml'
    - '.github/workflows/cloudflare-tunnel-validate.yaml'

jobs:
  scan-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Open Telemetry Collector Builder (ocb)
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with: # Grab a pure binary
        repo: cloudflare/cloudflared
        tag: 2023.5.0
        extension-matching: disable
        rename-to: cloudflared
        chmod: 0755 
    - name: Validate Cloudflared config
      run: |
        cloudflared --config='ingress/cloudflared/config.yaml' tunnel ingress validate
